# Generated by Django 5.2.6 on 2025-12-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace_App', '0003_perfilusuario_telefono_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado'), ('REACONDICIONADO', 'Reacondicionado'), ('VENDIDO', 'Vendido')], default='USADO', max_length=20),
        ),
    ]
